version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongo-me-rn
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=expense_manager

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-me-rn
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb://mongodb:27017/expense_manager # ← THIS WAS THE FIX

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-me-rn
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
